import { create } from 'storybook/theming';

export default create({
  base: 'light',
  colorPrimary: '#0e416c',
  colorSecondary: '#0e416c',
  appBg: '#FFF',
  appContentBg: '#FFF',
  appPreviewBg: '#FFF',
  appBorderColor: '#E9E9E9',
  appBorderRadius: 8,
  fontBase: "'Plus Jakarta Sans', sans-serif",
  fontCode: 'monospace',
  textColor: '#646464',
  textInverseColor: '#ffffff',
  textMutedColor: '#000000',
  barTextColor: '#ffffff',
  barHoverColor: '#ffffff',
  barSelectedColor: '#ffffff',
  barBg: '#0e416c',
  buttonBg: '#EBF7FD',
  buttonBorder: '#0e416c',
  booleanBg: '#EBF7FD',
  booleanSelectedBg: '#0e416c',
  inputBg: '#ffffff',
  inputBorder: '#CCCCCC',
  inputTextColor: '#646464',
  inputBorderRadius: 8,
  brandTitle: '</> APEX',
  brandImage: '/public/img/logo.svg',
  brandUrl: 'https://google.com',
  brandTarget: '_self',
  gridCellSize: 8,
});
